user = "root"              # your MySQL username
password = "SOHAM13@SQL"  # your MySQL password
host = "localhost"        # hostname (localhost or IP address)
port = 3306               # default MySQL port
database = "libradb"      # name of your MySQL database
password_encoded = quote_plus(password)

DATABASE_URI = "mysql+pymysql://{user}:{password_encoded}@{host}/{database}"
